In [9]:
import pandas as pd
import numpy as np
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\darri\appdata\roaming\python\python312\site-packages (2.2.2)

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
#pd.set_option("display.max_rows", None)
genres=pd.read_csv('ratings.csv')

In [11]:
genres.head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [12]:
genres.shape

(105339, 4)

In [13]:
genres.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [14]:
genres['timestamp']=pd.to_datetime(genres['timestamp'])

In [15]:
genres.dtypes

userId                int64
movieId               int64
rating              float64
timestamp    datetime64[ns]
dtype: object

In [16]:
genres.head()

   userId  movieId  rating                     timestamp
0       1       16     4.0 1970-01-01 00:00:01.217897793
1       1       24     1.5 1970-01-01 00:00:01.217895807
2       1       32     4.0 1970-01-01 00:00:01.217896246
3       1       47     4.0 1970-01-01 00:00:01.217896556
4       1       50     4.0 1970-01-01 00:00:01.217896523

In [17]:
movies=pd.read_csv('movies.csv')

In [18]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [19]:
movies.shape

(10329, 3)

In [20]:
movies.dtypes

movieId     int64
title      object
genres     object
dtype: object

In [21]:
movies.describe().T

,count,mean,std,min,25%,50%,75%,max
movieId,10329.0,31924.282893,37734.741149,1.0,3240.0,7088.0,59900.0,149532.0

In [22]:
genres.describe().T

,count,mean,min,25%,50%,75%,max,std
userId,105339.0,364.924539,1.0,192.0,383.0,557.0,668.0,197.486905
movieId,105339.0,13381.312477,1.0,1073.0,2497.0,5991.0,149532.0,26170.456869
rating,105339.0,3.51685,0.5,3.0,3.5,4.0,5.0,1.044872
timestamp,105339,1970-01-01 00:00:01.130423971,1970-01-01 00:00:00.828564954,1970-01-01 00:00:00.971100797,1970-01-01 00:00:01.115154056,1970-01-01 00:00:01.275495998,1970-01-01 00:00:01.452404919,NaN

In [23]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [24]:
# Split the 'genres' column and explode it into separate rows
movies["genres"] = movies["genres"].str.split("|")
movies = movies.explode("genres", ignore_index=True)

In [25]:
movies.head()

   movieId             title     genres
0        1  Toy Story (1995)  Adventure
1        1  Toy Story (1995)  Animation
2        1  Toy Story (1995)   Children
3        1  Toy Story (1995)     Comedy
4        1  Toy Story (1995)    Fantasy

In [26]:
movies["genres"].unique()

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'IMAX', 'War', 'Musical', 'Documentary',
       'Western', 'Film-Noir', '(no genres listed)'], dtype=object)

In [27]:
# IMAX and (no genres listed) are invalid genres
movies[(movies["genres"] != "(no genres listed)") & (movies["genres"] != "IMAX")]
movies=movies[(movies["genres"] != "(no genres listed)") & (movies["genres"] != "IMAX")]

In [28]:
movies["genres"].unique()

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'War', 'Musical', 'Documentary', 'Western',
       'Film-Noir'], dtype=object)

In [29]:

#merge movie2 and rating 
df=pd.merge(movies,genres,on=["movieId"],how="inner")

In [30]:
df.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure,2,5.0,1970-01-01 00:00:00.859046895
1,1,Toy Story (1995),Adventure,5,4.0,1970-01-01 00:00:01.303501039
2,1,Toy Story (1995),Adventure,8,5.0,1970-01-01 00:00:00.858610933
3,1,Toy Story (1995),Adventure,11,4.0,1970-01-01 00:00:00.850815810
4,1,Toy Story (1995),Adventure,14,4.0,1970-01-01 00:00:00.851766286

In [31]:
df.tail()

,movieId,title,genres,userId,rating,timestamp
278860,146878,Le Grand Restaurant (1966),Comedy,622,2.5,1970-01-01 00:00:01.447514637
278861,148238,A Very Murray Christmas (2015),Comedy,475,3.0,1970-01-01 00:00:01.451213043
278862,148626,The Big Short (2015),Drama,458,4.0,1970-01-01 00:00:01.452014749
278863,148626,The Big Short (2015),Drama,576,4.5,1970-01-01 00:00:01.451687664
278864,148626,The Big Short (2015),Drama,668,4.5,1970-01-01 00:00:01.451148148

In [32]:
df.isnull().sum()

movieId      0
title        0
genres       0
userId       0
rating       0
timestamp    0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
#popularity recommender system
popularity=df.groupby(['genres',"title"]).agg({"rating":['mean',"size"]}).reset_index()
popularity.columns=['Genres',"Title","Average_ratings","Number_of_Ratings"]
popularity

,Genres,Title,Average_ratings,Number_of_Ratings
0,Action,'71 (2014),3.500000,1
1,Action,'Hellboy': The Seeds of Creation (2004),3.000000,1
2,Action,10 to Midnight (1983),2.500000,1
3,Action,12 Rounds (2009),2.875000,4
4,Action,13 Assassins (Jûsan-nin no shikaku) (2010),3.500000,5
...,...,...,...,...
22941,Western,Wyatt Earp (1994),3.200000,30
22942,Western,Young Guns (1988),3.375000,36
22943,Western,Young Guns II (1990),3.083333,12
22944,Western,Young Ones (2014),2.000000,1
22945,Western,¡Three Amigos! (1986),3.012500,40

In [35]:
# DEMO OUTPUT
# genre=action
# threshold=50
# top=7
popularity[(popularity['Genres']==("Action"))&(popularity['Number_of_Ratings']>=50)].sort_values(by="Average_ratings",ascending=False).head(7)

,Genres,Title,Average_ratings,Number_of_Ratings
1179,Action,Princess Mononoke (Mononoke-hime) (1997),4.384615,52
1076,Action,North by Northwest (1959),4.273973,73
975,Action,"Matrix, The (1999)",4.264368,261
1433,Action,Star Wars: Episode V - The Empire Strikes Back...,4.228070,228
1331,Action,Seven Samurai (Shichinin no samurai) (1954),4.217742,62
1199,Action,Raiders of the Lost Ark (Indiana Jones and the...,4.212054,224
747,Action,Inception (2010),4.189320,103

In [36]:
#popularity recommender system funct
def TopNPopularMovies(genre,threshold,topN):
    popularity=df.groupby(['genres',"title"]).agg({"rating":['mean',"size"]}).reset_index()
    popularity.columns=['Genres',"Title","Average_ratings","Number_of_Ratings"]
    #filter the data
    topNrecommendations=popularity[(popularity['Genres'] == genre) & (popularity['Number_of_Ratings'] >= threshold)].sort_values(by="Average_ratings",ascending=False).head(topN)
    #output
    topNrecommendations['Sno.']=range(1, len(topNrecommendations) +1)
    topNrecommendations = topNrecommendations.reset_index(drop=True)
    topNrecommendations = topNrecommendations[['Sno.', 'Title', 'Average_ratings', 'Number_of_Ratings']]
    topNrecommendations.columns = ['Sno.', "Movie_Title", "Average_Movie_Rating", "Number_of_Reviews"]
    return topNrecommendations[["Sno.","Movie_Title","Average_Movie_Rating","Number_of_Reviews"]]

In [37]:
# DEMO OUTPUT
TopNPopularMovies(genre='Adventure', threshold=50, topN=7)

,Sno.,Movie_Title,Average_Movie_Rating,Number_of_Reviews
0,1,Princess Mononoke (Mononoke-hime) (1997),4.384615,52
1,2,Monty Python and the Holy Grail (1975),4.301948,154
2,3,North by Northwest (1959),4.273973,73
3,4,Spirited Away (Sen to Chihiro no kamikakushi) ...,4.236111,72
4,5,Star Wars: Episode V - The Empire Strikes Back...,4.228070,228
5,6,Seven Samurai (Shichinin no samurai) (1954),4.217742,62
6,7,Raiders of the Lost Ark (Indiana Jones and the...,4.212054,224

In [38]:
#content based recommender system
movies.head()

   movieId             title     genres
0        1  Toy Story (1995)  Adventure
1        1  Toy Story (1995)  Animation
2        1  Toy Story (1995)   Children
3        1  Toy Story (1995)     Comedy
4        1  Toy Story (1995)    Fantasy

In [39]:
 df_grouped = movies.groupby(["movieId", "title"])["genres"].apply(" ".join).reset_index()

In [40]:
 df_grouped

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10317,146656,Creed (2015),Drama
10318,146684,Cosmic Scrat-tastrophe (2015),Animation Children Comedy
10319,146878,Le Grand Restaurant (1966),Comedy
10320,148238,A Very Murray Christmas (2015),Comedy
10321,148626,The Big Short (2015),Drama

In [41]:
movies= df_grouped[['title','genres']]

In [42]:
movies.head()

,title,genres
0,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,Jumanji (1995),Adventure Children Fantasy
2,Grumpier Old Men (1995),Comedy Romance
3,Waiting to Exhale (1995),Comedy Drama Romance
4,Father of the Bride Part II (1995),Comedy

In [43]:
#tfidf vectorizer>>>to convert genres into vectors
from sklearn.feature_extraction.text import TfidfVectorizer
# Initialize TfidfVectorizer with n-gram range (1,3)
tf=TfidfVectorizer(analyzer="word",ngram_range=(1,3),stop_words="english")
tf

TfidfVectorizer(ngram_range=(1, 3), stop_words='english')

In [44]:
tf.fit_transform(movies['genres'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 44067 stored elements and shape (10322, 535)>

In [45]:
tf_matrix=tf.fit_transform(movies['genres'])
tf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 44067 stored elements and shape (10322, 535)>

In [46]:
from sklearn.metrics.pairwise import cosine_similarity
#Cosine similarity measures the angle between two vectors in a multi-dimensional space.
#It ranges from 0 to 1 (if vectors are normalized).
#1 means the vectors (documents) are identical.
#0 means they have no similarity.

In [47]:
cosine_sim=cosine_similarity(tf_matrix,tf_matrix)
cosine_sim

array([[1.        , 0.20408755, 0.05024022, ..., 0.13130407, 0.13130407,
        0.        ],
       [0.20408755, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05024022, 0.        , 1.        , ..., 0.382625  , 0.382625  ,
        0.        ],
       ...,
       [0.13130407, 0.        , 0.382625  , ..., 1.        , 1.        ,
        0.        ],
       [0.13130407, 0.        , 0.382625  , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(10322, 10322))

In [48]:
indices=pd.Series(movies.index,index=movies["title"])
indices.head()

title
Toy Story (1995)                      0
Jumanji (1995)                        1
Grumpier Old Men (1995)               2
Waiting to Exhale (1995)              3
Father of the Bride Part II (1995)    4
dtype: int64

In [49]:
# DEMO
index=indices["'71 (2014)"]
index

np.int64(10112)

In [109]:
scores=list(enumerate(cosine_sim[index]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.026934966057758122)),
 (4, np.float64(0.0)),
 (5, np.float64(0.10228104820798074)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.20252715005865068)),
 (9, np.float64(0.09396567753283752)),
 (10, np.float64(0.026934966057758122)),
 (11, np.float64(0.0)),
 (12, np.float64(0.0)),
 (13, np.float64(0.12244109179408538)),
 (14, np.float64(0.045844697311389966)),
 (15, np.float64(0.04208530048149644)),
 (16, np.float64(0.04386490518918696)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.17083870878318194)),
 (20, np.float64(0.046305834482728875)),
 (21, np.float64(0.042357688851800156)),
 (22, np.float64(0.10228104820798074)),
 (23, np.float64(0.020331139157054694)),
 (24, np.float64(0.04386490518918696)),
 (25, np.float64(0.12244109179408538)),
 (26, np.float64(0.02801859740652764)),
 (27, np.float64(0.04386490518918696)),
 (28, np.float64(0.010138690734679604)),
 (29, np.float64(0.04208530048149644)),
 (30, np.float64(0.12244109179408538)),
 (31, np.float64(0.03614469266252693)),
 (32, np.float64(0.0)),
 (33, np.float64(0.02801859740652764)),
 (34, np.float64(0.04386490518918696)),
 (35, np.float64(0.04208530048149644)),
 (36, np.float64(0.0)),
 (37, np.float64(0.12244109179408538)),
 (38, np.float64(0.2169782061948198)),
 (39, np.float64(0.0857252269302305)),
 (40, np.float64(0.12244109179408538)),
 (41, np.float64(0.051791638383035944)),
 (42, np.float64(0.177631599217364)),
 (43, np.float64(0.04386490518918696)),
 (44, np.float64(0.07498849294283758)),
 (45, np.float64(0.011157735262772564)),
 (46, np.float64(0.04386490518918696)),
 (47, np.float64(0.04198041052990044)),
 (48, np.float64(0.026934966057758122)),
 (49, np.float64(0.03463206046714643)),
 (50, np.float64(0.0)),
 (51, np.float64(0.12244109179408538)),
 (52, np.float64(0.12244109179408538)),
 (53, np.float64(0.026934966057758122)),
 (54, np.float64(0.03309955615845088)),
 (55, np.float64(0.0)),
 (56, np.float64(0.3576970618131369)),
 (57, np.float64(0.12244109179408538)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.0)),
 (61, np.float64(0.08242833194914113)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0698138265517019)),
 (65, np.float64(0.20252715005865068)),
 (66, np.float64(0.04754364319350469)),
 (67, np.float64(0.2169782061948198)),
 (68, np.float64(0.04386490518918696)),
 (69, np.float64(0.04754364319350469)),
 (70, np.float64(0.08242833194914113)),
 (71, np.float64(0.20870327022860047)),
 (72, np.float64(0.3576970618131369)),
 (73, np.float64(0.02801859740652764)),
 (74, np.float64(0.022887113640191175)),
 (75, np.float64(0.04754364319350469)),
 (76, np.float64(0.04386490518918696)),
 (77, np.float64(0.04754364319350469)),
 (78, np.float64(0.04386490518918696)),
 (79, np.float64(0.0812705223432854)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.1481307615688775)),
 (83, np.float64(0.12244109179408538)),
 (84, np.float64(0.06646364089878302)),
 (85, np.float64(0.0)),
 (86, np.float64(0.026934966057758122)),
 (87, np.float64(0.09396567753283752)),
 (88, np.float64(0.04754364319350469)),
 (89, np.float64(0.04208530048149644)),
 (90, np.float64(0.3576970618131369)),
 (91, np.float64(0.0)),
 (92, np.float64(0.0)),
 (93, np.float64(0.03614469266252693)),
 (94, np.float64(0.0)),
 (95, np.float64(0.04386490518918696)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.3413054997975913)),
 (99, np.float64(0.2146024920042367)),
 (100, np.float64(0.04278761070128289)),
 (101, np.float64(0.03309955615845088)),
 (102, np.float64(0.12244109179408538)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.04208530048149644)),
 (106, np.float64(0.0)),
 (107, np.float64(0.12244109179408538)),
 (108, np.float64(0.0)),
 (109, np.float64(0.018417079171922746)),
 (110, np.float64(0.12244109179408538)),
 (111, np.float64(0.0)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.04386490518918696)),
 (115, np.float64(0.18576277173677733)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.12244109179408538)),
 (119, np.float64(0.04386490518918696)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.17083870878318194)),
 (123, np.float64(0.0)),
 (124, np.float64(0.12244109179408538)),
 (125, np.float64(0.2146024920042367)),
 (126, np.float64(0.03463206046714643)),
 (127, np.float64(0.25735018252333763)),
 (128, np.float64(0.0326024511162095)),
 (129, np.float64(0.04278761070128289)),
 (130, np.float64(0.12244109179408538)),
 (131, np.float64(0.12774748178901113)),
 (132, np.float64(0.04754364319350469)),
 (133, np.float64(0.13836921680395198)),
 (134, np.float64(0.0)),
 (135, np.float64(0.021542261176443332)),
 (136, np.float64(0.02846045153773473)),
 (137, np.float64(0.80055736943094)),
 (138, np.float64(0.0)),
 (139, np.float64(0.03745241023716322)),
 (140, np.float64(0.025218771997412442)),
 (141, np.float64(0.10228104820798074)),
 (142, np.float64(0.023275887084197124)),
 (143, np.float64(0.23571881994365218)),
 (144, np.float64(0.017000559019776568)),
 (145, np.float64(0.069263544091305)),
 (146, np.float64(0.04754364319350469)),
 (147, np.float64(0.08242833194914113)),
 (148, np.float64(0.034734813885628414)),
 (149, np.float64(0.0)),
 (150, np.float64(0.12244109179408538)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0)),
 (153, np.float64(0.04754364319350469)),
 (154, np.float64(0.04386490518918696)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0616494991011288)),
 (157, np.float64(0.04386490518918696)),
 (158, np.float64(0.0422445483727881)),
 (159, np.float64(0.12244109179408538)),
 (160, np.float64(0.10228104820798074)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.18576277173677733)),
 (165, np.float64(0.04386490518918696)),
 (166, np.float64(0.12244109179408538)),
 (167, np.float64(0.04754364319350469)),
 (168, np.float64(0.026934966057758122)),
 (169, np.float64(0.0)),
 (170, np.float64(0.06559037185393521)),
 (171, np.float64(0.018272841349778912)),
 (172, np.float64(0.18576277173677733)),
 (173, np.float64(0.031819064040502144)),
 (174, np.float64(0.04386490518918696)),
 (175, np.float64(0.0)),
 (176, np.float64(0.20252715005865068)),
 (177, np.float64(0.04754364319350469)),
 (178, np.float64(0.0)),
 (179, np.float64(0.04386490518918696)),
 (180, np.float64(0.04462067086614579)),
 (181, np.float64(0.12244109179408538)),
 (182, np.float64(0.0)),
 (183, np.float64(0.12244109179408538)),
 (184, np.float64(0.0)),
 (185, np.float64(0.12244109179408538)),
 (186, np.float64(0.2169782061948198)),
 (187, np.float64(0.04386490518918696)),
 (188, np.float64(0.0)),
 (189, np.float64(0.3576970618131369)),
 (190, np.float64(0.04754364319350469)),
 (191, np.float64(0.12244109179408538)),
 (192, np.float64(0.0)),
 (193, np.float64(0.04386490518918696)),
 (194, np.float64(0.0)),
 (195, np.float64(0.026934966057758122)),
 (196, np.float64(0.3576970618131369)),
 (197, np.float64(0.18576277173677733)),
 (198, np.float64(0.1481307615688775)),
 (199, np.float64(0.0)),
 (200, np.float64(0.3576970618131369)),
 (201, np.float64(0.3576970618131369)),
 (202, np.float64(0.0)),
 (203, np.float64(0.026934966057758122)),
 (204, np.float64(0.12244109179408538)),
 (205, np.float64(0.0)),
 (206, np.float64(0.04754364319350469)),
 (207, np.float64(0.052834941389302)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.18576277173677733)),
 (212, np.float64(0.02801859740652764)),
 (213, np.float64(0.029317245379621163)),
 (214, np.float64(0.0)),
 (215, np.float64(0.04208530048149644)),
 (216, np.float64(0.0)),
 (217, np.float64(0.04208530048149644)),
 (218, np.float64(0.0)),
 (219, np.float64(0.04386490518918696)),
 (220, np.float64(0.0)),
 (221, np.float64(0.20252715005865068)),
 (222, np.float64(0.0)),
 (223, np.float64(0.0326024511162095)),
 (224, np.float64(0.12244109179408538)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.07498849294283758)),
 (228, np.float64(0.0)),
 (229, np.float64(0.2146024920042367)),
 (230, np.float64(0.04462067086614579)),
 (231, np.float64(0.12244109179408538)),
 (232, np.float64(0.02801859740652764)),
 (233, np.float64(0.12244109179408538)),
 (234, np.float64(0.018613091674970366)),
 (235, np.float64(0.08408131228272359)),
 (236, np.float64(0.0)),
 (237, np.float64(0.04208530048149644)),
 (238, np.float64(0.12244109179408538)),
 (239, np.float64(0.04386490518918696)),
 (240, np.float64(0.12244109179408538)),
 (241, np.float64(0.04754364319350469)),
 (242, np.float64(0.015281096115225434)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.12244109179408538)),
 (247, np.float64(0.0)),
 (248, np.float64(0.12244109179408538)),
 (249, np.float64(0.3576970618131369)),
 (250, np.float64(0.026934966057758122)),
 (251, np.float64(0.12244109179408538)),
 (252, np.float64(0.04208530048149644)),
 (253, np.float64(0.10228104820798074)),
 (254, np.float64(0.0)),
 (255, np.float64(0.04208530048149644)),
 (256, np.float64(0.3576970618131369)),
 (257, np.float64(0.1870684453189892)),
 (258, np.float64(0.20870327022860047)),
 (259, np.float64(0.0)),
 (260, np.float64(0.15950836899062842)),
 (261, np.float64(0.12244109179408538)),
 (262, np.float64(0.12244109179408538)),
 (263, np.float64(0.12244109179408538)),
 (264, np.float64(0.04386490518918696)),
 (265, np.float64(0.04386490518918696)),
 (266, np.float64(0.07052961579010282)),
 (267, np.float64(0.04754364319350469)),
 (268, np.float64(0.0)),
 (269, np.float64(0.12244109179408538)),
 (270, np.float64(0.12244109179408538)),
 (271, np.float64(0.04754364319350469)),
 (272, np.float64(0.12244109179408538)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.012908711459000504)),
 (276, np.float64(0.6978933201282018)),
 (277, np.float64(0.04462067086614579)),
 (278, np.float64(0.020513935033677478)),
 (279, np.float64(0.04208530048149644)),
 (280, np.float64(0.177631599217364)),
 (281, np.float64(0.03746060918824952)),
 (282, np.float64(0.12244109179408538)),
 (283, np.float64(0.04754364319350469)),
 (284, np.float64(0.04754364319350469)),
 (285, np.float64(0.0)),
 (286, np.float64(0.12244109179408538)),
 (287, np.float64(0.04031309732755557)),
 (288, np.float64(0.0764271121477406)),
 (289, np.float64(0.015033259417447301)),
 (290, np.float64(0.04505775837835856)),
 (291, np.float64(0.12244109179408538)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.12244109179408538)),
 (295, np.float64(0.07498849294283758)),
 (296, np.float64(0.2169782061948198)),
 (297, np.float64(0.12244109179408538)),
 (298, np.float64(0.08242833194914113)),
 (299, np.float64(0.0)),
 (300, np.float64(0.12774748178901113)),
 (301, np.float64(0.12244109179408538)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0)),
 (305, np.float64(0.04754364319350469)),
 (306, np.float64(0.029317245379621163)),
 (307, np.float64(0.012794101569790252)),
 (308, np.float64(0.0)),
 (309, np.float64(0.20870327022860047)),
 (310, np.float64(0.069896711824675)),
 (311, np.float64(0.026934966057758122)),
 (312, np.float64(0.04754364319350469)),
 (313, np.float64(0.057610498668415236)),
 (314, np.float64(0.12244109179408538)),
 (315, np.float64(0.0)),
 (316, np.float64(0.11377488615665961)),
 (317, np.float64(0.0)),
 (318, np.float64(0.12244109179408538)),
 (319, np.float64(0.09592776487255637)),
 (320, np.float64(0.026934966057758122)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0)),
 (323, np.float64(0.011375633096371256)),
 (324, np.float64(0.12244109179408538)),
 (325, np.float64(0.05070971086933203)),
 (326, np.float64(0.03674301045723745)),
 (327, np.float64(0.0)),
 (328, np.float64(0.12244109179408538)),
 (329, np.float64(0.09592776487255637)),
 (330, np.float64(0.04754364319350469)),
 (331, np.float64(0.026934966057758122)),
 (332, np.float64(0.18576277173677733)),
 (333, np.float64(0.0)),
 (334, np.float64(0.12244109179408538)),
 (335, np.float64(0.1481307615688775)),
 (336, np.float64(0.0760799295491281)),
 (337, np.float64(0.0)),
 (338, np.float64(0.08242833194914113)),
 (339, np.float64(0.06289484616025932)),
 (340, np.float64(0.04386490518918696)),
 (341, np.float64(0.04192291402381999)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0857252269302305)),
 (344, np.float64(0.12244109179408538)),
 (345, np.float64(0.12244109179408538)),
 (346, np.float64(0.09592776487255637)),
 (347, np.float64(0.12244109179408538)),
 (348, np.float64(0.13108329123415502)),
 (349, np.float64(0.0857252269302305)),
 (350, np.float64(0.04208530048149644)),
 (351, np.float64(0.0)),
 (352, np.float64(0.051791638383035944)),
 (353, np.float64(0.12244109179408538)),
 (354, np.float64(0.0)),
 (355, np.float64(0.06785035042138013)),
 (356, np.float64(0.0764271121477406)),
 (357, np.float64(0.12244109179408538)),
 (358, np.float64(0.04208530048149644)),
 (359, np.float64(0.0)),
 (360, np.float64(0.12244109179408538)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0)),
 (363, np.float64(0.06291843838260482)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.12244109179408538)),
 (367, np.float64(0.0)),
 (368, np.float64(0.08005172419016698)),
 (369, np.float64(0.017000559019776568)),
 (370, np.float64(0.18576277173677733)),
 (371, np.float64(0.1481307615688775)),
 (372, np.float64(0.12244109179408538)),
 (373, np.float64(0.04386490518918696)),
 (374, np.float64(0.03912518690484608)),
 (375, np.float64(0.047379930752724696)),
 (376, np.float64(0.12244109179408538)),
 (377, np.float64(0.0)),
 (378, np.float64(0.04754364319350469)),
 (379, np.float64(0.04208530048149644)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.09396567753283752)),
 (383, np.float64(0.0)),
 (384, np.float64(0.3576970618131369)),
 (385, np.float64(0.0)),
 (386, np.float64(0.07517084477832922)),
 (387, np.float64(0.12244109179408538)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0)),
 (390, np.float64(0.04462067086614579)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.04386490518918696)),
 (395, np.float64(0.0)),
 (396, np.float64(0.12244109179408538)),
 (397, np.float64(0.0)),
 (398, np.float64(0.04754364319350469)),
 (399, np.float64(0.018417079171922746)),
 (400, np.float64(0.12244109179408538)),
 (401, np.float64(0.0)),
 (402, np.float64(0.3576970618131369)),
 (403, np.float64(0.017000559019776568)),
 (404, np.float64(0.2146024920042367)),
 (405, np.float64(0.18576277173677733)),
 (406, np.float64(0.02485954498360132)),
 (407, np.float64(0.06753014966743251)),
 (408, np.float64(0.0)),
 (409, np.float64(0.04386490518918696)),
 (410, np.float64(0.2146024920042367)),
 (411, np.float64(0.069263544091305)),
 (412, np.float64(0.3413054997975913)),
 (413, np.float64(0.12754291768376722)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.04386490518918696)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.04754364319350469)),
 (420, np.float64(0.13836921680395198)),
 (421, np.float64(0.1481307615688775)),
 (422, np.float64(0.12244109179408538)),
 (423, np.float64(0.04754364319350469)),
 (424, np.float64(0.029317245379621163)),
 (425, np.float64(0.10228104820798074)),
 (426, np.float64(0.07202652673445958)),
 (427, np.float64(0.3576970618131369)),
 (428, np.float64(0.2146024920042367)),
 (429, np.float64(0.12244109179408538)),
 (430, np.float64(0.04201578327120817)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.04386490518918696)),
 (434, np.float64(0.0)),
 (435, np.float64(0.18576277173677733)),
 (436, np.float64(0.12244109179408538)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0857252269302305)),
 (439, np.float64(0.09396567753283752)),
 (440, np.float64(0.12244109179408538)),
 (441, np.float64(0.058695406988656273)),
 (442, np.float64(0.0)),
 (443, np.float64(0.04386490518918696)),
 (444, np.float64(0.0)),
 (445, np.float64(0.04754364319350469)),
 (446, np.float64(0.12244109179408538)),
 (447, np.float64(0.03489163534000023)),
 (448, np.float64(0.17507942214840794)),
 (449, np.float64(0.0)),
 (450, np.float64(0.018613091674970366)),
 (451, np.float64(0.2146024920042367)),
 (452, np.float64(0.12244109179408538)),
 (453, np.float64(0.04386490518918696)),
 (454, np.float64(0.12244109179408538)),
 (455, np.float64(0.41682584573574355)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.04386490518918696)),
 (460, np.float64(0.04754364319350469)),
 (461, np.float64(0.2079519311651809)),
 (462, np.float64(0.0)),
 (463, np.float64(0.07181492643884388)),
 (464, np.float64(0.0)),
 (465, np.float64(0.07492256366413427)),
 (466, np.float64(0.41682584573574355)),
 (467, np.float64(0.12244109179408538)),
 (468, np.float64(0.12244109179408538)),
 (469, np.float64(0.12244109179408538)),
 (470, np.float64(0.12244109179408538)),
 (471, np.float64(0.2169782061948198)),
 (472, np.float64(0.04754364319350469)),
 (473, np.float64(0.12244109179408538)),
 (474, np.float64(0.02801859740652764)),
 (475, np.float64(0.0)),
 (476, np.float64(0.03502230140920878)),
 (477, np.float64(0.04386490518918696)),
 (478, np.float64(0.12244109179408538)),
 (479, np.float64(0.12244109179408538)),
 (480, np.float64(0.12244109179408538)),
 (481, np.float64(0.12244109179408538)),
 (482, np.float64(0.026934966057758122)),
 (483, np.float64(0.18576277173677733)),
 (484, np.float64(0.08242833194914113)),
 (485, np.float64(0.026934966057758122)),
 (486, np.float64(0.04190826463872277)),
 (487, np.float64(0.09204726129130589)),
 (488, np.float64(0.12244109179408538)),
 (489, np.float64(0.026961308637727947)),
 (490, np.float64(0.09396567753283752)),
 (491, np.float64(0.08131059325424116)),
 (492, np.float64(0.029317245379621163)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.04275975864536827)),
 (496, np.float64(0.179377103339651)),
 (497, np.float64(0.2146024920042367)),
 (498, np.float64(0.07492256366413427)),
 (499, np.float64(0.0)),
 (500, np.float64(0.03397104776182089)),
 (501, np.float64(0.12244109179408538)),
 (502, np.float64(0.04754364319350469)),
 (503, np.float64(0.04386490518918696)),
 (504, np.float64(0.0326024511162095)),
 (505, np.float64(0.0)),
 (506, np.float64(0.04754364319350469)),
 (507, np.float64(0.04754364319350469)),
 (508, np.float64(0.04754364319350469)),
 (509, np.float64(0.04754364319350469)),
 (510, np.float64(0.04386490518918696)),
 (511, np.float64(0.12244109179408538)),
 (512, np.float64(0.04754364319350469)),
 (513, np.float64(0.0)),
 (514, np.float64(0.017000559019776568)),
 (515, np.float64(0.12244109179408538)),
 (516, np.float64(0.0)),
 (517, np.float64(0.04754364319350469)),
 (518, np.float64(0.0)),
 (519, np.float64(0.0)),
 (520, np.float64(0.03957798457315394)),
 (521, np.float64(0.0)),
 (522, np.float64(0.053626739972986774)),
 (523, np.float64(0.01607066237858314)),
 (524, np.float64(0.10228104820798074)),
 (525, np.float64(0.04030084982547921)),
 (526, np.float64(0.010809842552191687)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.05762511030355978)),
 (532, np.float64(0.12244109179408538)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.04386490518918696)),
 (536, np.float64(0.0)),
 (537, np.float64(0.15950836899062842)),
 (538, np.float64(0.0)),
 (539, np.float64(0.026223674104054576)),
 (540, np.float64(0.04066481142962554)),
 (541, np.float64(0.0)),
 (542, np.float64(0.04386490518918696)),
 (543, np.float64(0.3576970618131369)),
 (544, np.float64(0.04754364319350469)),
 (545, np.float64(0.0)),
 (546, np.float64(0.04754364319350469)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.12244109179408538)),
 (550, np.float64(0.0)),
 (551, np.float64(0.3576970618131369)),

In [57]:
matched=sorted(scores,key=lambda x:x[1],reverse=True)[:5]
matched

[(5454, np.float64(1.0)),
 (6353, np.float64(1.0)),
 (7070, np.float64(1.0)),
 (7614, np.float64(1.0)),
 (8147, np.float64(1.0))]

In [58]:
matched=[i[0] for i in matched]
matched

[5454, 6353, 7070, 7614, 8147]

In [59]:
movies.iloc[matched]

,title,genres
5454,Throne of Blood (Kumonosu jô) (1957),Action Drama Thriller War
6353,Battle Royale 2: Requiem (Batoru rowaiaru II: ...,Action Drama Thriller War
7070,Army of Shadows (L'armée des ombres) (1969),Action Drama Thriller War
7614,Rambo (Rambo 4) (2008),Action Drama Thriller War
8147,"Hurt Locker, The (2008)",Action Drama Thriller War

In [60]:
movies.head()

,title,genres
0,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,Jumanji (1995),Adventure Children Fantasy
2,Grumpier Old Men (1995),Comedy Romance
3,Waiting to Exhale (1995),Comedy Drama Romance
4,Father of the Bride Part II (1995),Comedy

In [95]:
#content based recommender sys funct
def recommendation_genre(movie_df,similarity_matrix,movie_title,topN):
    #indices for all movies
    indices=pd.Series(movies.index,index=movies["title"])
    #index of target movie
    index=indices[movie_title]
    #cosine similarity scores
    cosine_scores=list(enumerate(cosine_sim[index]))
    cosine_scores=sorted(cosine_scores,key=lambda x:x[1],reverse=True)[:topN + 1]
    #extract the matching movies
    matched=[i[0] for i in cosine_scores]
    matching_df=movie_df.iloc[matched]
    #filter out the target movie
    matching_df=matching_df[matching_df["title"]!=movie_title]

    #output
    matching_df.rename(columns={"title":"Movie Title"},inplace=True)
    matching_df["Sno."]=range(1,len(matching_df)+1)
    matching_df.index=range(0,len(matching_df))
    return matching_df[["Sno.","Movie Title"]].head(topN)

In [96]:
#test case
recommendation_genre(movie_df=movies,similarity_matrix=cosine_sim,movie_title="Toy Story (1995)",topN=10)

   Sno.                                        Movie Title
0     1                                        Antz (1998)
1     2                                 Toy Story 2 (1999)
2     3     Adventures of Rocky and Bullwinkle, The (2000)
3     4                   Emperor's New Groove, The (2000)
4     5                              Monsters, Inc. (2001)
5     6  DuckTales: The Movie - Treasure of the Lost La...
6     7                                   Wild, The (2006)
7     8                              Ant Bully, The (2006)
8     9                             Shrek the Third (2007)
9    10                     Tale of Despereaux, The (2008)

In [97]:
from ipywidgets import *
#popularity
#inputs
genres=Dropdown(options=list(set(movies['genres'])),description="Genres",style={"description_width":"initial"})
num_reviews=IntText(description="Minimum Reviews",style={"description_width":"initial"})  
num_recommendations_1=IntText(description="Number of Recommendations",style={"description_width":"initial"}) 

#tabs
b1=Button(description="RECOMMEND ME",style={"description_width":"initial"})      
h1=HBox([num_reviews,num_recommendations_1])     
popularity_tab=VBox([genres,h1,b1]) 

#content bases system
title=Textarea(description="Movie Title",style={"description_width":"initial"})  
num_recommendations_2=IntText(description="Number of Recommendations",style={"description_width":"initial"})  

#tabs      
h2=HBox([title,num_recommendations_2]) 
b2=Button(description="RECOMMEND ME",style={"description_width":"initial"}) 

content_tab=VBox([h2,b2])

#creating final tabs
tabs=[popularity_tab,content_tab]
wid=widgets.Tab(tabs)

#set titles to the tabs
names=["Popularity Based Recommendations","Content Based Recommendations"]
[wid.set_title(i,title) for i,title in enumerate(names)]

[None, None]

In [98]:
#setting uo events to respond when clicked upon

# Output Widget
output = Output()

#popularity
def b1_clicked(b):
    global output
    output=TopNPopularMovies(genre=genres.value,threshold=num_reviews.value,topN=num_recommendations_1.value)
b1.on_click(b1_clicked)

#content
def b2_clicked(b):
    global output
    result=recommendation_genre(movie_df=movies,similarity_matrix=cosine_sim,movie_title=title.value,topN=num_recommendations_2.value)
    output=result
b2.on_click(b2_clicked)

In [108]:
# Display the widgets
display(wid, output)

Tab(children=(VBox(children=(Dropdown(description='Genres', index=198, options=('Comedy Horror Romance', 'Chil…

,Sno.,Movie_Title,Average_Movie_Rating,Number_of_Reviews
0,1,All Quiet on the Western Front (1930),4.500000,13
1,2,Paths of Glory (1957),4.500000,19
2,3,Ran (1985),4.403226,31
3,4,Schindler's List (1993),4.296371,248
4,5,Henry V (1989),4.272727,22
5,6,Battlestar Galactica (2003),4.263158,19
6,7,Life Is Beautiful (La Vita è bella) (1997),4.253425,73
7,8,Breaker Morant (1980),4.192308,13
8,9,Lawrence of Arabia (1962),4.166667,60
9,10,Grave of the Fireflies (Hotaru no haka) (1988),4.166667,18